sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t azminavanzara/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true azminavanzara/docker-react npm run test 

